= Erastus Brewster Kimball (1798 - 1879)

TBD narrative goes here


== Vital Stats


* Sex: M
* Birth: 5 APR 1798
* Birthplace: Preston, New London, Connecticut, USA
* Death: 22 AUG 1879
* Deathplace: Uncasville, New London, Connecticut, USA
* Buried:  Buried Comstock Cemetery, Uncasville CT
----
2 PLAC Buried Comstock Cemetery, Uncasville CT, Buried Comstock Cemetery, Uncasville CT, Comstock Cemetery, Uncasville, New London, Connecticut, USA
----

* Age at Death: 81


== Family
* Mother: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G6/gen6.MMMMPM.adoc[Lucy Hall Brewster (1773 - ?)]


* Father: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G6/gen6.MMMMPP.adoc[Nathaniel Kimball (1768 - 1822)]


* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.MMMM.adoc[Sarah Lavinia Kimball (1830 - 1909)]



== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.MMMMP.adoc[Book page]
* https://cfsjksas.gigalixirapp.com/person?p=p0661[Dev website]
* WeRelate TBD
* MyHeritage TBD
* Geni TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.P.adoc[Herbert Kirkwood Sparrell (1899 - 1978)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.PM.adoc[Lavinia Elizabeth Strong (1875 - 1941)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.PMM.adoc[Alice Virginia Edgecomb (1850 - 1914)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.PMMM.adoc[Sarah Lavinia Kimball (1830 - 1909)]

* Erastus Brewster Kimball (1798 - 1879)

=== Lineage #2
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.M.adoc[Marion F Fisher (1904 - 2002)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.MM.adoc[Ida A Hurlburt (1874 - 1965)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MMM.adoc[Martha Avery Edgecomb (1855 - 1939)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.MMMM.adoc[Sarah Lavinia Kimball (1830 - 1909)]

* Erastus Brewster Kimball (1798 - 1879)


== Other
census: 
----
2 DATE 1860
2 PLAC The Town Of Montville, New London, Connecticut, USA
2 AGE 61-62
----

notes: <p>Uncasville is a village in the town of Montville CT.</p><p><p></p></p><p>An Advertisment in The Norwich CT Newspaper of Nov 4, 1822 invited anyone interested in becoming a blacksmith apprentice to 
----
2 CONC apply to Erastus B. Kimball in Preston.</p>
----

occupation: Blacksmith in Preston
----
2 DATE 1822
2 PLAC Preston, New London, Connecticut, USA
2 AGE 23-24
----
Blacksmith in Montville (US Census)
----
2 DATE 1860
2 PLAC Montville, New London, Connecticut, USA
2 AGE 61-62
----


== Sources
* @S32@
----
2 PAGE https://www.myheritage.com/research/record-10127-1620295/erastus-b-kimball-in-1860-united-states-federal-census
2 QUAY 4
2 DATA
3 TEXT Erastus B Kimball
4 CONC Gender: Male
4 CONC Birth: Circa 1797 - Connecticut, United States
4 CONC Residence: 1860 - The Town Of Montville, New London, Connecticut, USA
4 CONC Age: 63
4 CONC Wife (implied): Lydia Kimball
4 CONC Census:   Township:The Town Of MontvilleSeries:M653Image:136  County:New LondonSheet:37  State:ConnecticutFamily:936  Date:1860-00-00Line:33 See household members
4 CONC <a id='household'></a>Household
4 CONC Relation to head; Name; Age
4 CONC Head (implied); <a href="https://www.myheritage.com/research/record-10127-1620295/erastus-b-kimball-in-1860-united-states-federal-census?s=20674952">Erastus B Kimball</a>; 63
4 CONC Wife (implied); <a href="https://www.myheritage.com/research/record-10127-1620296/lydia-kimball-in-1860-united-states-federal-census?s=20674952">Lydia Kimball</a>; 58
----

