= James Newton Sparrell (1770 - 1826)

Narrative TBD


== Vital Stats


* Sex: M
* Birth: 7 APR 1770
* Birthplace: Scituate, Plymouth, Massachusetts, USA
* Death: 3 NOV 1826
* Deathplace: Scituate, Plymouth, Massachusetts, USA
* Buried: 

* PLAC Norwell Center Cemetery, Norwell, Plymouth, Massachusetts, USA
* Age at Death: 56


== Family
* Mother: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G7/gen7.PPPPPPM.Ruth_Vinal.adoc[Ruth Vinal (1746 - 1810)]

* Father: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G7/gen7.PPPPPPP.James_Newton_Sparrell.adoc[James Newton Sparrell (1740 - 1773)]

* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.PPPPP.James_Newton_Sparrell.adoc[James Newton Sparrell (1798 - 1859)]


== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G6/gen6.PPPPPP.James_Newton_Sparrell.adoc[Book Link]
https://cfsjksas.gigalixirapp.com/person?p=p0530http://localhost:4000/person?p=p0530https://cfsjksas.gigalixirapp.com/adoc?p=p0530http://localhost:4000/adoc?p=p0530* Geni TBD
* MyHeritage TBD
* https://www.werelate.org/wiki/Person:James_Sparrell_%282%29[WeRelate]
* WikiTree TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.P.Herbert_Kirkwood_Sparrell.adoc[Herbert Kirkwood Sparrell (1899 - 1978)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.PP.Charles_Herbert_Sparrell.adoc[Charles Herbert Sparrell (1873 - 1961)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.PPP.Herbert_Kirkwood_Sparrell.adoc[Herbert Kirkwood Sparrell (1847 - 1923)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.PPPP.James_Newton_Sparrell.adoc[James Newton Sparrell (1825 - 1877)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.PPPPP.James_Newton_Sparrell.adoc[James Newton Sparrell (1798 - 1859)]
* gen6.PPPPPP.James_Newton_Sparrell_(1770 - 1826)


== Other
event: 

* TYPE Fact 5

* DATE 26 AUG 1809

* AGE 39 "Yeoman" (deed)

* TYPE Fact 4

* DATE 29 MAY 1802

* AGE 32 Called "Captain"

* TYPE Title (Facts Pg) Constable thru 1806

* TYPE Appointed

* DATE 1804

* AGE 33-34 Default of Debts-Plymouth Court

* TYPE Fact 4

* DATE NOV 1819

* AGE 49 Deputy Sheriff for Plymouth County

* TYPE Appointed

* DATE 1816

* AGE 45-46 Hog Reeve

* TYPE Appointed

* DATE 1802

* AGE 31-32 Property seized by sheriff for debt

* TYPE Fact 7

* DATE 26 NOV 1819

* AGE 49 Recruiting Committee

* TYPE Appointed

* DATE 1812

* AGE 41-42 Surveyor of Highways thru 1817/1823

* TYPE Appointed

* DATE 1800

* AGE 29-30 _ELEC of Sparrell, James Newton, Moderator-Special Town Meeting

* TYPE _ELEC

* DATE 12 SEP 1814

* AGE 44
notes: JAMES NEWTON SPARRELL II and RACHEL TURNER SPARRELL James Newton Sparrell II was born in Scituate, Massachusetts Bay Colonyon 7 April 1770. He was the second of three children of Captain James Newton Sparrell and Ruth Vinal Sparrell. From March 1771 until 1778, Thefamily lived in a house that formerly stood by Scituate Harbor north ofthe present town pier. On 4 June 1775, James and his sisters, Elizabethand Hannah were christened and his mother, Ruth admitted to membershipin the Scituate First Parish Meeting House. Ruth later married Capt. Joshua Jenkins, another sea captain, in the same church on 24 December1778. After Ruth?s remarriage, the family moved to Captain Jenkin?s house on the Beaverdam Road site where the Clipper Ship Motel now stands. Joshua had been lost at sea and one of James?s sisters had died by the time of the 1790 census which lists Ruth Jenkins as the head of family. By 1787,James Newton Sparrell had followed his father and stepfather to sea and by 1797 he was referred to as "Captain Sparrell". On 11 June 1797, James married Rachel Turner in the Second Parish Meeting House in the south end of Scituate (Now Norwell). On 8 July 1797, James purchased three-quarters of  a dwelling house, three-quarters of a barn and 16-1/2 acres of land from Abijah and Mary Turner Otis (Rachel?ssister) and conveyed to Mary Otis three parcels of land and half a dwelling. On the same date, the Otises conveyed to James five acres of saltmeadow by the North River and 3-1/2 acres of wood lot on Simon?s Hillset off as Mary?s portion of the estate of her father John Turner. On 8April 1799, James acquired additional property from Abijah and Mary including five acres of salt marsh on the North River and ¼ of a pew in theSecond Parish Meeting House also left to Mary by her father. Some ofthese transactions involved portions of the original land grant on theriveralloted in the 1630?s to Ruth?s ancestor and first settler Humphrey Turner. James is referred to as "Captain" in Town Meeting Minutes (1801) and 2nd Parish Church Records (1810). He is recorded as a "mariner" in the 1797 land deeds. In deeds dated 1799 and 1802 he is recorded as "yeoman" and in deeds and other legal documents from March 1808 on he is titled "gentleman". (A yeoman was a small farmer who owned and worked his land.A gentleman was an owner of extensive property holdings who employed farm laborers to do the work.) James apparently retired from the sea after his marriage and settled ashore as a farmer. In 1805, James appears in the Plymouth custom house register. He and others including Thatcher Tilden (his neighbor and husband of  Lucy Turner Tilden, Rachel?s sister)  are listed as owners of the 200 ton, three-masted full-rigged ship Florenzo of Scituate. On 29 May 1802, James purchased a 20 acre farm next to his farm from Samuel Foster. In August 1809 he acquired ( with Thomas Cushing) 4-3/4 acres of salt meadow between the third and fourth cliffs. From that pointon his land purchases were scattered and appear to be speculative investments. These included 50 acres of land between Colman?s Hills and thehighway (now Stockbridge Road) and a house with 1-1/2 acres of land fromJ. Robert Northey ( March 1812). Between 1800 and 1817, James held a number of minor town offices and appointments. These included Surveyor of Highways (14 years), Constable, Hog Reeve, Moderator (1814 special town meeting), Methodist Society Inquiry Committee, Election Committee, Workhouse Inquiry Committee (1811), etc. The Methodist Committee reported that the society was not a menace to public order and should be allowed to establish a church. The Workhouse Committee recommended that the town meeting establish a home for orphans, idiots, and the destitute elderly rather than to continue to auction them off to the lowest bidder ( The alms house was bu
occupation: "Mariner" (deed)

* DATE 7 JUL 1797

* AGE 27"Yeoman" (deed)

* DATE 8 APR 1799

* AGE 29
title: Captain

== Sources

