= Ida A Hurlburt (1874 - 1965)

TBD narrative goes here


== Vital Stats


* Sex: F
* Birth: 14 NOV 1874
* Birthplace: Worcester, Worcester, Massachusetts, USA
* Death: 3 JAN 1965
* Deathplace: North Kingstown, Washington, Rhode Island, USA
* Buried: 
----
2 PLAC Comstock Cemetery, Uncasville, New London, Connecticut, USA
----

* Age at Death: 90
* Death Cause: Coronary Thrombosis


== Family
* Mother: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MMM.adoc[Martha Avery Edgecomb (1855 - 1939)]


* Father: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MMP.adoc[Charles Henry Hurlburt (1849 - 1930)]


* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.M.adoc[Marion F Fisher (1904 - 2002)]



== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.MM.adoc[Book page]
* https://cfsjksas.gigalixirapp.com/person?p=p0072[Dev website]
* https://www.werelate.org/wiki/Person:Ida_Hurlburt_%281%29[WeRelate]
* https://www.myheritage.com/profile-20674952-23000286/ida-a-hurlburt-fisher[MyHeritage]
* https://www.geni.com/people/Ida-Hurlburt/6000000219136898849[Geni]

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.M.adoc[Marion F Fisher (1904 - 2002)]

* Ida A Hurlburt (1874 - 1965)


== Other
event:  _MEDICAL of Hurlburt, Ida A.
----
2 TYPE _MEDICAL
----
 Coronary Thrombosis
----
2 TYPE _DCAUSE
----

notes: Sometime after Albert's death Ida and Marion moved down to New London .World War I was coming on and Ida got a job at the Electric Boat Company as a secretary. While there she met and married her seco
----
2 CONC nd husband, Cyril Hewitt. Cyril was a draftstman at the shipyard. Cyril lived in Uncasville and Ida's father had retired from the railroad and moved back there into Ida's grandmother's house. Cyril an
2 CONC d Ida built property on the west side of the Norwich-New London Road just North of the Waterford-Montville line. They built a house and started a chicken farm, raising White Leghorn hens to provide wh
2 CONC ite eggs. (White eggs found a ready market among the New Yorkers who were moving into Connecticut. Native New Englanders produced and used only brown eggs.) <p></p> <p>The poultry business was a succe
2 CONC ss, but Cyril was not well and and diedin the 1920's. Ida ran the farm alone until about 1940. She was in her60's and the work got too hard for her. She went to work atConecticutCollege as a salad pre
2 CONC parer in the dining room. Sometime in the 50's she retired from that. After an accident in which she demolished her car, Marion convinced her to sell her home. Kirkwood built her a small house next to
2 CONC  theirs in Wickford RI and there she lived for the rest of her life.
----

occupation: Poultry Farmer,
----
2 DATE ABT 1925
2 PLAC Uncasville, New London, Connecticut, USA
2 AGE About 50-51
----
Stenographer -Electric Boat Co.,
----
2 DATE 1920
2 PLAC Groton, New London, Connecticut, USA
2 AGE 45-46
----
Secretary-Typist,
----
2 DATE ABT 1895
2 PLAC Boston, Suffolk, Massachusetts, USA
2 AGE About 20-21
----


== Sources
